/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef S3EAPSALAR_AUTODEFS_H
#define S3EAPSALAR_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_APSALAR_NAME "s3eApsalar"
#define S3E_EXT_APSALAR_HASH 0xa99b67b4

#endif /* !S3EAPSALAR_AUTODEFS_H */
