/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */

#include "s3eExt.h"
#include "IwDebug.h"
#include "s3eDevice.h"


#include "s3eApsalar.h"

/**
 * Definitions for functions types passed to/from s3eExt interface
 */
typedef       void(*s3eApStart_t)(const char *apiKey, const char *apiSecret);
typedef       void(*s3eApRestart_t)(const char *apiKey, const char *apiSecret);
typedef       bool(*s3eApStarted_t)();
typedef       void(*s3eApEnd_t)();
typedef       void(*s3eApLogEvent_t)(const char *name);

/**
 * struct that gets filled in by s3eApsalarRegister
 */
typedef struct s3eApsalarFuncs
{
    s3eApStart_t m_s3eApStart;
    s3eApRestart_t m_s3eApRestart;
    s3eApStarted_t m_s3eApStarted;
    s3eApEnd_t m_s3eApEnd;
    s3eApLogEvent_t m_s3eApLogEvent;
} s3eApsalarFuncs;

static s3eApsalarFuncs g_Ext;
static bool g_GotExt = false;
static bool g_TriedExt = false;
static bool g_TriedNoMsgExt = false;

static bool _extLoad()
{
    if (!g_GotExt && !g_TriedExt)
    {
        s3eResult res = s3eExtGetHash(0xa99b67b4, &g_Ext, sizeof(g_Ext));
        if (res == S3E_RESULT_SUCCESS)
            g_GotExt = true;
        else
            s3eDebugAssertShow(S3E_MESSAGE_CONTINUE_STOP_IGNORE,                 "error loading extension: s3eApsalar");
            
        g_TriedExt = true;
        g_TriedNoMsgExt = true;
    }

    return g_GotExt;
}

static bool _extLoadNoMsg()
{
    if (!g_GotExt && !g_TriedNoMsgExt)
    {
        s3eResult res = s3eExtGetHash(0xa99b67b4, &g_Ext, sizeof(g_Ext));
        if (res == S3E_RESULT_SUCCESS)
            g_GotExt = true;
        g_TriedNoMsgExt = true;
        if (g_TriedExt)
            g_TriedExt = true;
    }

    return g_GotExt;
}

s3eBool s3eApsalarAvailable()
{
    _extLoadNoMsg();
    return g_GotExt ? S3E_TRUE : S3E_FALSE;
}

void s3eApStart(const char *apiKey, const char *apiSecret)
{
    IwTrace(APSALAR_VERBOSE, ("calling s3eApsalar[0] func: s3eApStart"));

    if (!_extLoad())
        return;

#ifdef __mips
    // For MIPs platform we do not have asm code for stack switching 
    // implemented. So we make LoaderCallStart call manually to set GlobalLock
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    g_Ext.m_s3eApStart(*apiKey, *apiSecret);

#ifdef __mips
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return;
}

void s3eApRestart(const char *apiKey, const char *apiSecret)
{
    IwTrace(APSALAR_VERBOSE, ("calling s3eApsalar[1] func: s3eApRestart"));

    if (!_extLoad())
        return;

#ifdef __mips
    // For MIPs platform we do not have asm code for stack switching 
    // implemented. So we make LoaderCallStart call manually to set GlobalLock
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    g_Ext.m_s3eApRestart(*apiKey, *apiSecret);

#ifdef __mips
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return;
}

bool s3eApStarted()
{
    IwTrace(APSALAR_VERBOSE, ("calling s3eApsalar[2] func: s3eApStarted"));

    if (!_extLoad())
        return S3E_FALSE;

#ifdef __mips
    // For MIPs platform we do not have asm code for stack switching 
    // implemented. So we make LoaderCallStart call manually to set GlobalLock
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    bool ret = g_Ext.m_s3eApStarted();

#ifdef __mips
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return ret;
}

void s3eApEnd()
{
    IwTrace(APSALAR_VERBOSE, ("calling s3eApsalar[3] func: s3eApEnd"));

    if (!_extLoad())
        return;

#ifdef __mips
    // For MIPs platform we do not have asm code for stack switching 
    // implemented. So we make LoaderCallStart call manually to set GlobalLock
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    g_Ext.m_s3eApEnd();

#ifdef __mips
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return;
}

void s3eApLogEvent(const char *name)
{
    IwTrace(APSALAR_VERBOSE, ("calling s3eApsalar[4] func: s3eApLogEvent"));

    if (!_extLoad())
        return;

#ifdef __mips
    // For MIPs platform we do not have asm code for stack switching 
    // implemented. So we make LoaderCallStart call manually to set GlobalLock
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    g_Ext.m_s3eApLogEvent(*name);

#ifdef __mips
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return;
}
