/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
/*
 * This file contains the automatically generated loader-side
 * functions that form part of the extension.
 *
 * This file is awlays compiled into all loaders but compiles
 * to nothing if this extension is not enabled in the loader
 * at build time.
 */
#include "s3eApsalar_autodefs.h"
#include "s3eEdk.h"
#include "s3eApsalar.h"
//Declarations of Init and Term functions
extern s3eResult s3eApsalarInit();
extern void s3eApsalarTerminate();


void s3eApsalarRegisterExt()
{
    /* fill in the function pointer struct for this extension */
    void* funcPtrs[12];
    funcPtrs[0] = (void*)s3eApStart;
    funcPtrs[1] = (void*)s3eApRestart;
    funcPtrs[2] = (void*)s3eApStarted;
    funcPtrs[3] = (void*)s3eApEnd;
    funcPtrs[4] = (void*)s3eApLogEvent;
    funcPtrs[5] = (void*)s3eApDictCreate;
    funcPtrs[6] = (void*)s3eApDictAddString;
    funcPtrs[7] = (void*)s3eApDictAddInt;
    funcPtrs[8] = (void*)s3eApDictAddFloat;
    funcPtrs[9] = (void*)s3eApDictAddDict;
    funcPtrs[10] = (void*)s3eApLogEventWithArgs;
    funcPtrs[11] = (void*)s3eApSetFBAppId;

    /*
     * Flags that specify the extension's use of locking and stackswitching
     */
    int flags[12] = { 0 };

    /*
     * Register the extension
     */
    s3eEdkRegister("s3eApsalar", funcPtrs, sizeof(funcPtrs), flags, s3eApsalarInit, s3eApsalarTerminate, 0);
}

#if !defined S3E_BUILD_S3ELOADER

#if defined S3E_EDK_USE_STATIC_INIT_ARRAY
int s3eApsalarStaticInit()
{
    void** p = g_StaticInitArray;
    void* end = p + g_StaticArrayLen;
    while (*p) p++;
    if (p < end)
        *p = (void*)&s3eApsalarRegisterExt;
    return 0;
}

int g_s3eApsalarVal = s3eApsalarStaticInit();

#elif defined S3E_EDK_USE_DLLS
S3E_EXTERN_C S3E_DLL_EXPORT void RegisterExt()
{
    s3eApsalarRegisterExt();
}
#endif

#endif
